CREATE TABLE symptom_mapping (
    mapping_id INTEGER PRIMARY KEY AUTOINCREMENT,
    symptoms TEXT,
    specialty TEXT
);

INSERT INTO symptom_mapping (symptoms, specialty) VALUES 
('Blurred vision, eye strain', 'Ophthalmologist'),
('Double vision, eye pain, light sensitivity', 'Ophthalmologist'),
('Red eyes, discharge, swollen eyelids', 'Ophthalmologist'),
('Headache, dizziness', 'Neurologist'),
('Migraine, nausea, light sensitivity', 'Neurologist'),
('Numbness, tingling in limbs, balance issues', 'Neurologist'),
('Knee pain, joint issues', 'Orthopedic'),
('Back pain, stiffness, limited movement', 'Orthopedic'),
('Shoulder pain, reduced range of motion, muscle weakness', 'Orthopedic'),
('Skin rash, itching', 'Dermatologist'),
('Acne, oily skin, facial inflammation', 'Dermatologist'),
('Hair loss, scalp flaking, patchy bald spots', 'Dermatologist'),
('Chest pain, palpitations', 'Cardiologist'),
('Shortness of breath on exertion, ankle swelling, fatigue', 'Cardiologist'),
('High blood pressure, headache, blurred vision', 'Cardiologist'),
('Cough, wheezing', 'Pulmonologist'),
('Chronic cough, sputum, breathlessness', 'Pulmonologist'),
('Snoring, daytime sleepiness, nighttime breathing pauses', 'Pulmonologist'),
('Stomach ache, indigestion', 'Gastroenterologist'),
('Acid reflux, heartburn, sour taste in mouth', 'Gastroenterologist'),
('Abdominal bloating, constipation, irregular bowel movements', 'Gastroenterologist'),
('Anxiety, insomnia', 'Psychiatrist'),
('Low mood, loss of interest, appetite change', 'Psychiatrist'),
('Panic attacks, chest tightness, fear episodes', 'Psychiatrist'),
('Frequent urination, excessive thirst, unexplained weight loss', 'Endocrinologist'),
('Thyroid swelling, weight fluctuation, temperature intolerance', 'Endocrinologist'),
('Painful urination, lower abdominal pain, fever', 'Urologist'),
('Blood in urine, flank pain, urinary urgency', 'Urologist'),
('Irregular periods, severe cramps, pelvic pain', 'Gynecologist'),
('Abnormal vaginal discharge, itching, burning sensation', 'Gynecologist'),
('Ear pain, hearing loss, ringing in ears', 'ENT Specialist'),
('Sore throat, sinus congestion, nasal blockage', 'ENT Specialist'),
('Toothache, gum bleeding, jaw swelling', 'Dentist'),
('Loose stools, vomiting, dehydration signs', 'General Physician'),
('Fever, body ache, sore throat, fatigue', 'General Physician'),
('Sudden weakness on one side, slurred speech, facial droop', 'Emergency Medicine');